apiVersion: v1
kind: Service
metadata:
  name: upload-csv-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: upload-csv-gke
  sessionAffinity: None
  type: NodePort